<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from de.systopia.segmentation/xml/schema/CRM/Segmentation/SegmentationOrder.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d70820632278d8ebc3755bed3c8da2d7)
 */
use CRM_Segmentation_ExtensionUtil as E;

/**
 * Database access object for the SegmentationOrder entity.
 */
class CRM_Segmentation_DAO_SegmentationOrder extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_segmentation_order';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique SegmentationOrder ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Campaign
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $campaign_id;

  /**
   * FK to SegmentationIndex
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $segment_id;

  /**
   * Order index from 1..n (highest to lowest)
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $order_number;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $bundle;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $text_block;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_segmentation_order';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Segmentation Orders') : E::ts('Segmentation Order');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'campaign_id', 'civicrm_campaign', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'segment_id', 'civicrm_segmentation_index', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique SegmentationOrder ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_segmentation_order.id',
          'table_name' => 'civicrm_segmentation_order',
          'entity' => 'SegmentationOrder',
          'bao' => 'CRM_Segmentation_DAO_SegmentationOrder',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'campaign_id' => [
          'name' => 'campaign_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Campaign ID'),
          'description' => E::ts('FK to Campaign'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_segmentation_order.campaign_id',
          'table_name' => 'civicrm_segmentation_order',
          'entity' => 'SegmentationOrder',
          'bao' => 'CRM_Segmentation_DAO_SegmentationOrder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Campaign_DAO_Campaign',
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'segment_id' => [
          'name' => 'segment_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Segment ID'),
          'description' => E::ts('FK to SegmentationIndex'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_segmentation_order.segment_id',
          'table_name' => 'civicrm_segmentation_order',
          'entity' => 'SegmentationOrder',
          'bao' => 'CRM_Segmentation_DAO_SegmentationOrder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Segmentation_DAO_SegmentationIndex',
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'order_number' => [
          'name' => 'order_number',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Order Number'),
          'description' => E::ts('Order index from 1..n (highest to lowest)'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_segmentation_order.order_number',
          'table_name' => 'civicrm_segmentation_order',
          'entity' => 'SegmentationOrder',
          'bao' => 'CRM_Segmentation_DAO_SegmentationOrder',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'bundle' => [
          'name' => 'bundle',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Bundle'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_segmentation_order.bundle',
          'table_name' => 'civicrm_segmentation_order',
          'entity' => 'SegmentationOrder',
          'bao' => 'CRM_Segmentation_DAO_SegmentationOrder',
          'localizable' => 0,
          'html' => [
            'type' => 'String',
          ],
          'add' => NULL,
        ],
        'text_block' => [
          'name' => 'text_block',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Text Block'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_segmentation_order.text_block',
          'table_name' => 'civicrm_segmentation_order',
          'entity' => 'SegmentationOrder',
          'bao' => 'CRM_Segmentation_DAO_SegmentationOrder',
          'localizable' => 0,
          'html' => [
            'type' => 'String',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'segmentation_order', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'segmentation_order', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
