-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_segmentation_exclude`;
DROP TABLE IF EXISTS `civicrm_activity_contact_segmentation`;
DROP TABLE IF EXISTS `civicrm_segmentation_order`;
DROP TABLE IF EXISTS `civicrm_segmentation_index`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_segmentation_index
-- *
-- *******************************************************/
CREATE TABLE `civicrm_segmentation_index` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique SegmentationIndex ID',
  `name` varchar(255) NULL COMMENT 'Name of the index',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_segmentation_order
-- *
-- *******************************************************/
CREATE TABLE `civicrm_segmentation_order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique SegmentationOrder ID',
  `campaign_id` int unsigned NULL COMMENT 'FK to Campaign',
  `segment_id` int unsigned NULL COMMENT 'FK to SegmentationIndex',
  `order_number` int unsigned NULL COMMENT 'Order index from 1..n (highest to lowest)',
  `bundle` varchar(255) NULL,
  `text_block` varchar(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_segmentation_order_campaign_id FOREIGN KEY (`campaign_id`) REFERENCES `civicrm_campaign`(`id`),
  CONSTRAINT FK_civicrm_segmentation_order_segment_id FOREIGN KEY (`segment_id`) REFERENCES `civicrm_segmentation_index`(`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_activity_contact_segmentation
-- *
-- *******************************************************/
CREATE TABLE `civicrm_activity_contact_segmentation` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ActivityContactSegmentation ID',
  `activity_contact_id` int unsigned NOT NULL COMMENT 'FK to ActivityContact',
  `segment_id` int unsigned NOT NULL COMMENT 'FK to SegmentationIndex',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_activity_contact_segmentation_activity_contact_id FOREIGN KEY (`activity_contact_id`) REFERENCES `civicrm_activity_contact`(`id`),
  CONSTRAINT FK_civicrm_activity_contact_segmentation_segment_id FOREIGN KEY (`segment_id`) REFERENCES `civicrm_segmentation_index`(`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_segmentation_exclude
-- *
-- *******************************************************/
CREATE TABLE `civicrm_segmentation_exclude` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique SegmentationExclude ID',
  `campaign_id` int unsigned NOT NULL COMMENT 'FK to Campaign',
  `segment_id` int unsigned NOT NULL COMMENT 'FK to SegmentationIndex',
  `contact_id` int unsigned NOT NULL COMMENT 'FK to Contact',
  `membership_id` int unsigned NULL COMMENT 'FK to Membership',
  `created_date` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date/Time the exclusion was created',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_segmentation_exclude_campaign_id FOREIGN KEY (`campaign_id`) REFERENCES `civicrm_campaign`(`id`),
  CONSTRAINT FK_civicrm_segmentation_exclude_segment_id FOREIGN KEY (`segment_id`) REFERENCES `civicrm_segmentation_index`(`id`),
  CONSTRAINT FK_civicrm_segmentation_exclude_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`),
  CONSTRAINT FK_civicrm_segmentation_exclude_membership_id FOREIGN KEY (`membership_id`) REFERENCES `civicrm_membership`(`id`)
)
ENGINE=InnoDB;
